### ISSUE TITLE
bug for pvpython

### ISSUE THREAD

**Issue by snow-stone** [snow-stone/python#4]
nu_mean_slice_xNormal-logScale.py $someDir $someDistance $someString 7051aa8

gives

```python
Traceback (most recent call last):
  File "nu_mean_slice_xNormal-logScale.py", line 2242, in <module>
    slice1Display.ScaleArrayComponent = ''
  File "/home/hluo/bin/ParaView/ParaView-5.6.0-RC2-Qt5-MPI-Linux-64bit/lib/python2.7/site-packages/paraview/servermanager.py", line 471, in __setattr__
    raise ValueError("%s is not a valid value for attribute %s." % (value, name))
ValueError:  is not a valid value for attribute ScaleArrayComponent.
```

works for 4D not for 6D may be this is because the slice is out of data range

**Comment by snow-stone** [comment]
@snow-stone have resolved the issue 7157c38 

Confirming the error is "slice out of range" but "del clip3" won't work. I just re-trace via python consol in paraview:
1. Removing every clip which is unecessary
2. Therefore there is only one slice and changing color palette in this version 7157c38
